#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: test_route
#          uri: http://localhost:7000/coupon/coupon/testconfig
##          uri: http://localhost:7000/coupon/coupon
#          predicates:
#          - Method=GET,POST
##            - Query=url, test.
spring:
  cloud:
    gateway:
      routes:
#        - id: admin_route
#          uri: lb://renrenfast
#          predicates:
#            - Path=/api/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=green,baidu
        - id: product_route
          uri: lb://product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # 库存服务
        - id: ware_route
          uri: lb://ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # 第三方服务
        - id: third_party_route
          uri: lb://thirdparty
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}
#        - id: member_route
#            uri: lb://member
#            predicates:
#              - Path=/api/member/**
#            filters:
#              - RewritePath=/api/(?<segment>.*),/$\{segment}
        # renrenfast后台服务
        - id: admin_route
          uri: lb://renrenfast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

#            下面这个未生效或者是我写错了 上面这个访问成功应该是：http://localhost:88/?green=1
#        - id: path_route
#          uri: https://www.baidu.com
#          predicates:
#            - Path=/red/**,/blue/**
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: method_route
#          uri: http://localhost:7000/coupon/coupon/list
#          predicates:
#            - Method=GET,POST