server:
  port: 11000

spring:
  profiles:
    active: common
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${wareSqlUrl}
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: ${nacosIp}
  application:
    name: ware
  jackson:
    date-format: yyyy-MM-dd

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      #主键自增
      id-type: auto